exchange_fee = 0.001
transaction_slippage = 0.01
query_limit = 2000
min_profit = 0.1
trade_duration_ms = 86400000
history_num_candles = 10000

[strong_points]
min_domain = 4

[export]
strong_point_length = 100
detail_view_len = 32
predict_candles_forward = 32
